Action:

  Info:
    description: Tell you which components of the SOC are on this host,\n if you specify the component it will only show information about it
    command_description: (--info | --info "component1" "component2")

  Healthcheck:
    description: Tell you if the components of the SOC on this host are healthy,\n if you specify the component it will only show information about it
    command_description: (--healthcheck | --healthcheck "component1" "component2")

  Install:
    description: Try to install the given component on host if possible,\n You need to specify at least a component,\n You should specify option relative to the component,\n look at --list-install-option
    command_description: (--install "component1" "component2")

  Config:
    description: Try to apply some configuration on the component on this host if possible.\n You need to specify at least a component.\n You should specify option relative to the component,\n look at --list-config-option
    command_description: (--config "component1")

  Repair:
    description: Try to fix a bad install of the given components.\n You need to specify at least a component.
    command_description: (--repair "component1" "component2")


Components: 

  Wazuh-Indexer:
    type: service
    role: SIEM
    description: >
      The Wazuh indexer is a highly scalable, full-text search and analytics engine.\n
      This Wazuh central component indexes and stores alerts generated by the Wazuh server and provides near real-time data search and analytics capabilities.\n
      The Wazuh indexer can be configured as a single-node or multi-node cluster, providing scalability and high availability.
    actions:
      - Info
      - Healthcheck
      - Install
      - Config
      - Repair
    
    platform:
      admin_rights_needed: True

      minimum_ram: 4 #Gb
      minimum_cpu_core: 2 

      recommended_ram: 16 #Gb
      recommended_free_space: 250 #Gb
      recommended_cpu_core: 8
      recommended_os:
        Linux:
          Amazon Linux:
            package: rpm
            version 2: 
              architecture: None
            version 2023: 
              architecture: None
            
          Ubuntu:
            package: deb
            version 16.04: 
              architecture: None
            version 18.04: 
              architecture: None
            version 20.04: 
              architecture: None
            version 22.04: 
              architecture: None
            version 24.04: 
              architecture: None       
          
          CentOS:
            package: rpm
            version 7: 
              architecture: None    
            version 8: 
              architecture: None   

          Red Hat Enterprise Linux:
            package: rpm
            version 7: 
              architecture: None    
            version 8: 
              architecture: None   
            version 9: 
              architecture: None               

        Windows:
          Windows:
            package: None
            version XP and later:
              architecture:
                - 32bit
                - 64bit


        # Windows: None
        MacOs: None

    
    options: # THIS IS THE ONLY PART YOU SHOULD CUSTOMIZE
      wazuh-indexer-ip: "127.0.0.1" # <- change this
      wazuh-indexer-port: 1515


  Wazuh-Server:
    type: service
    role: SIEM
    description: >
      The Wazuh server component analyzes the data received from the agents,\n
      triggering alerts when threats or anomalies are detected.\n
      It is also used to manage the agents configuration remotely and monitor their status.
    actions:
      - Info
      - Healthcheck
      - Install
      - Config
      - Repair

    platform:
      admin_rights_needed: True

      minimum_ram: 2 #Gb
      minimum_cpu_core: 2 

      recommended_ram: 4 #Gb
      recommended_free_space: 30 #Gb
      recommended_cpu_core: 8
      recommended_os:
        Linux:
          Amazon Linux:
            package: rpm
            version 2: 
              architecture: None
            version 2023: 
              architecture: None
            
          Ubuntu:
            package: deb
            version 16.04: 
              architecture: None
            version 18.04: 
              architecture: None
            version 20.04: 
              architecture: None
            version 22.04: 
              architecture: None
            version 24.04: 
              architecture: None       
          
          CentOS:
            package: rpm
            version 7: 
              architecture: None    
            version 8: 
              architecture: None   

          Red Hat Enterprise Linux:
            package: rpm
            version 7: 
              architecture: None    
            version 8: 
              architecture: None   
            version 9: 
              architecture: None               

        Windows: None
        MacOs: None

    options: # THIS IS THE ONLY PART YOU SHOULD CUSTOMIZE
      wazuh-server-ip: "127.0.0.1" # <- change this
      wazuh-server-port: 1515


  Wazuh-Dashboard:
    type: service
    role: SIEM
    description: >
      The Wazuh dashboard is a flexible and intuitive web user interface for mining, analyzing, and visualizing security events and alerts data.\n
      It is also used for the management and monitoring of the Wazuh platform.\n
      Additionally, it provides features for role-based access control (RBAC) and single sign-on (SSO).
    actions:
      - Info
      - Healthcheck
      - Install
      - Config
      - Repair

    platform:
      admin_rights_needed: True
      
      minimum_ram: 4 #Gb
      minimum_cpu_core: 2 
      
      recommended_ram: 8 #Gb
      recommended_free_space: 30 #Gb
      recommended_cpu_core: 4
      recommended_os:
        Linux:
          Amazon Linux:
            package: rpm
            version 2: 
              architecture: None
            version 2023: 
              architecture: None
            
          Ubuntu:
            package: deb
            version 16.04: 
              architecture: None
            version 18.04: 
              architecture: None
            version 20.04: 
              architecture: None
            version 22.04: 
              architecture: None
            version 24.04: 
              architecture: None       
          
          CentOS:
            package: rpm
            version 7: 
              architecture: None    
            version 8: 
              architecture: None   

          Red Hat Enterprise Linux:
            package: rpm
            version 7: 
              architecture: None    
            version 8: 
              architecture: None   
            version 9: 
              architecture: None               

        Windows: None
        MacOs: None


    options: # THIS IS THE ONLY PART YOU SHOULD CUSTOMIZE
      wazuh-dashboard-ip: "127.0.0.1" # <- change this
      wazuh-dashboard-port: 1515


  Wazuh-Agent:
    type: service
    role: XDR
    description: >
      The Wazuh agent runs on Linux, Windows, macOS, Solaris, AIX, and other operating systems.\n
      It can be deployed to laptops, desktops, servers, cloud instances, containers, or virtual machines.\n
      The agent helps to protect your system by providing threat prevention, detection, and response capabilities.\n
      It is also used to collect different types of system and application data that it forwards to the Wazuh server through an encrypted and authenticated channel.
    actions:
      - Info
      - Healthcheck
      - Install
      - Config
      - Repairs

    platform:
      admin_rights_needed: True

      minimum_ram: 4 #Gb
      minimum_cpu_core: 2 

      recommended_ram: 8 #Gb
      recommended_free_space: 30 #Gb
      recommended_cpu_core: 4
      recommended_os:
        Linux:
          Amazon Linux:
            package: rpm
            version 1 and later: 
              architecture:
                - x86_64
                - aarch64
          CentOS:
            package: rpm
            version 6 and later: 
              architecture:
                - xi386
                - x86_64
                - aarch64
                - armhf
            version 5: 
              architecture:
                - xi386
                - x86_64
          Debian:
            package: deb
            version 7 and later:
              architecture:
                - xi386
                - x86_64
                - aarch64
                - armhf
          Fedora:
            package: rpm
            version 22 and later:
              architecture:
                  - xi386
                  - x86_64
                  - aarch64
                  - armhf 
          OpenSUSE:
            package: rpm
            version 42 and later:
              architecture:
                  - xi386
                  - x86_64
                  - aarch64
                  - armhf
          Oracle Linux:
            package: rpm
            version 6 and later: 
              architecture:
                - xi386
                - x86_64
                - aarch64
            version 5: 
              architecture:
                - xi386
                - x86_64
          Red Hat Enterprise Linux:
            package: rpm
            version 6 and later: 
              architecture:
                - xi386
                - x86_64
                - aarch64
            version 5: 
              architecture:
                - xi386
                - x86_64
          SUSE:
            package: rpm
            version 12:
              architecture:
                - xi386
                - x86_64
                - aarch64
                - armhf
            version 11:
              architecture:
                - xi386
                - x86_64
          Ubuntu:
            package: deb
            version 12 and later:
              architecture:
                - xi386
                - x86_64
                - aarch64
                - armhf
          Raspbian OS:
            package: deb
            version Buster and later:
              architecture:
                - aarch64
                - armhf
        Windows:
          Windows:
            package: None
            version XP and later:
              architecture:
                - 32bit
                - 64bit
        MacOs:
          MacOs:
            package: None
            version intel:
              architecture:
                - intel64
            version silicon:
              architecture:
                - arm64
        Solaris:
          Solaris:
            package: None
            version 10:
              architecture:
                - i386
                - SPARC
            version 11:
              architecture:
                - i386
                - SPARC

        Aix:
          Aix:
            package: rpm
            version 6.1 and later:  
              architecture:
                - PowerPC

        HP-UX:
          HP-UX:
            package: None
            version 11.31:
              architecture:
                - Itanium

    options: # THIS IS THE ONLY PART YOU SHOULD CUSTOMIZE
      wazuh-agent-ip: "127.0.0.1" # <- change this
      wazuh-agent-port: 1515

  SELKS:
    type: docker
    role: IDS
    description: >
      SELKS is a free, open-source, and turn-key Suricata network intrusion detection/protection system (IDS/IPS), \n
      network security monitoring (NSM) and threat hunting implementation created and maintained by Stamus Networks.
    actions:
      - Info
      - Healthcheck
      - Install
      - Config
      - Repair
    
    platform:
      admin_rights_needed: True

      minimum_ram: 10 #Gb
      minimum_cpu_core: 2 
      minimum_free_space: 15 #Gb 

      recommended_ram: 16 #Gb
      recommended_free_space: 200 #Gb
      recommended_cpu_core: 8
      recommended_os:
        Linux:
          Fedora:
            package: rpm
            version X: 
              architecture: None

          Ubuntu:
            package: deb
            version X: 
              architecture: None
          
          CentOS:
            package: rpm
            version X: 
              architecture: None    

          Red Hat Enterprise Linux:
            package: rpm
            version X: 
              architecture: None    

          Debian:
            package: deb
            version X: 
              architecture: None               

        Windows: None
        MacOs: None

    options: # THIS IS THE ONLY PART YOU SHOULD CUSTOMIZE
      selks-ip: "127.0.0.1" # <- change this
      selks-port: 1515